webhook:
  secret: ""
  ingress:
    annotations: {}
    host: ""
forwarder:
  ingress:
    annotations: {}
    host: ""
scaleDownAfter: 6s
controllerManager:
  manager:
    args:
      - --leader-elect
      - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image: willeam/review-app-operator
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  type: ClusterIP
kubernetesClusterDomain: cluster.local
