webhook:
  secret: ""
  ingress:
    annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
    tls: false
    host: "" # review-app-webhooks.example.com
forwarder:
  ingress:
    annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
    tls: false
    hosts:
      # The forwarder hosts MUST BE a wildcard DNS entry because only one ingress
      # is used to route requests to the forwarder.
      # - "*.review-apps.example.com"
      - ""
scaleDownAfter: 1h
controllerManager:
  manager:
    args:
      - --leader-elect
      - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image: willeam/review-app-operator
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  type: ClusterIP
kubernetesClusterDomain: cluster.local
