webhook:
  # The secret will be created if it does not exist
  secretKeyRef:
    name: webhook-secret
    key: webhook-secret
  ingress:
    annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
    tls: false
    host: "" # review-app-webhooks.example.com
forwarder:
  ingress:
    annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
    tls: false
    hosts:
      # The forwarder hosts MUST BE a wildcard DNS entry because only one ingress
      # is used to route requests to the forwarder.
      # - "*.review-apps.example.com"
      - ""
scaleDownAfter: 1h
namespaces:
  - review-apps
controllerManager:
  manager:
    image: ghcr.io/wille/review-app-operator
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  type: ClusterIP
kubernetesClusterDomain: cluster.local
