# Scale down deployments that has not been accessed for some time
scaleDownAfter: 1h
# scaleDownAfter: Never

# The active namespaces
namespaces:
  - review-apps

image: ghcr.io/wille/review-app-operator

webhook:
  replicas: 1

  # The webhook secret that will be used by the CI to trigger pull request events
  # The secret will be created if it does not exist.
  secretKeyRef:
    name: webhook-secret
    key: webhook-secret
  ingress:
    ingressClassName: ""
    annotations: {}
    # Enable cert-manager
    # cert-manager.io/cluster-issuer: letsencrypt
    # tls: true
    tls: false

    # The host for the webhook
    # review-app-webhooks.example.com
    host: ""

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
forwarder:
  replicas: 1
  ingress:
    ingressClassName: ""
    annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt
    tls: false
    hosts:
      # The forwarder hosts MUST BE a wildcard DNS entry because only one ingress
      # is used to route requests to the forwarder.
      # - "*.review-apps.example.com"
      - ""
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

controllerManager:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceAccount:
  annotations: {}

kubernetesClusterDomain: cluster.local
