version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
  exclusions:
    presets:
      - comments
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll

formatters:
  enable:
    - gofmt
    - goimports
