apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-forwarder
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
  {{ toYaml .Values.webhook.ingress.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
    - '{{ .Values.forwarder.ingress.host }}'
    secretName: {{ include "chart.fullname" . }}-forwarder-secret
  rules:
  - host: '{{ required "forwarder.ingress.host must be set" .Values.forwarder.ingress.host }}'
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-forwarder'
            port:
              number: 6969
        path: /
        pathType: Prefix

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-forwarder
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: forwarder
      port: 6969
      targetPort: 6969
