apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-forwarder
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.webhook.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.forwarder.ingress.tls }}
  tls:
  - hosts: {{ toYaml .Values.forwarder.ingress.hosts | nindent 4 }}
    secretName: {{ include "chart.fullname" . }}-forwarder-tls
  {{- end }}
  rules:
  {{- range .Values.forwarder.ingress.hosts }}
  - host: {{ required "host must not be empty" . | toYaml }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "chart.fullname" $ }}-forwarder
            port:
              number: 6969
        path: /
        pathType: Prefix
  {{- end}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-forwarder
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: forwarder
      port: 6969
      targetPort: 6969
