apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - reviewapps.william.nu
  resources:
  - pullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reviewapps.william.nu
  resources:
  - pullrequests/finalizers
  verbs:
  - update
- apiGroups:
  - reviewapps.william.nu
  resources:
  - pullrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - reviewapps.william.nu
  resources:
  - reviewapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reviewapps.william.nu
  resources:
  - reviewapps/finalizers
  verbs:
  - update
- apiGroups:
  - reviewapps.william.nu
  resources:
  - reviewapps/status
  verbs:
  - get
  - patch
  - update

{{ $fullname := include "chart.fullname" . }}
{{ $labels := include "chart.labels" . }}
{{- range $namespace := .Values.namespaces -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}-manager-rolebinding
  namespace: {{ $namespace }}
  labels:
  {{- $labels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullname }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ $fullname }}-controller-manager
  namespace: {{ $.Release.Namespace }}
{{- end }}