apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-pullrequest-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rac.william.nu
  resources:
  - pullrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rac.william.nu
  resources:
  - pullrequests/status
  verbs:
  - get