apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controllerManager.type }}
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080