apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.secretKeyRef.name }}
data:
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace .Values.webhook.secretKeyRef.name }}

  {{- if or (not $old_sec) (not $old_sec.data) }}
  {{ .Values.webhook.secretKeyRef.key }}: {{ randAlphaNum 32 | b64enc }}
  {{ else }}
  {{ .Values.webhook.secretKeyRef.key }}: {{ index $old_sec.data .Values.webhook.secretKeyRef.key }}
  {{ end }}
