apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: webhook
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080