# permissions for end users to view pullrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rac2
    app.kubernetes.io/managed-by: kustomize
  name: pullrequest-viewer-role
rules:
  - apiGroups:
      - rac.william.nu
    resources:
      - pullrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rac.william.nu
    resources:
      - pullrequests/status
    verbs:
      - get
