# permissions for end users to edit pullrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rac2
    app.kubernetes.io/managed-by: kustomize
  name: pullrequest-editor-role
rules:
  - apiGroups:
      - rac.william.nu
    resources:
      - pullrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rac.william.nu
    resources:
      - pullrequests/status
    verbs:
      - get
