# permissions for end users to view reviewapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: review-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: reviewapp-viewer-role
rules:
  - apiGroups:
      - reviewapps.william.nu
    resources:
      - reviewapps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - reviewapps.william.nu
    resources:
      - reviewapps/status
    verbs:
      - get
