# permissions for end users to edit reviewapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rac2
    app.kubernetes.io/managed-by: kustomize
  name: reviewapp-editor-role
rules:
- apiGroups:
  - rac.william.nu
  resources:
  - reviewapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rac.william.nu
  resources:
  - reviewapps/status
  verbs:
  - get
