apiVersion: rac.william.nu/v1alpha1
kind: ReviewApp
metadata:
  name: reviewapp-sample
  labels:
    mylabel: mylabel
spec:
  github:
    githubToken: "githubToken"
  deployments:
    # A staging environment pointing to your read only production database
    - name: prod
      spec:
        # It's recommended to run your staging containers on a separate node pool
        # nodeSelector:
        #   node-role.kubernetes.io/staging: "true"
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
    - name: staging
      spec:
        containers:
          - name: nginx
            image: nginx:1.20
            ports:
              - containerPort: 80
    # A staging environment pointing to your staging database
  ingresses:
    - name: myingress
      spec:
        rules:
          - host: test
            http:
              paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                      name: myservice
                      port:
                        number: 80
