apiVersion: rac.william.nu/v1alpha1
kind: ReviewApp
metadata:
  name: reviewapp-sample
  labels:
    mylabel: mylabel
spec:
  deployments:
    # A staging environment pointing to your read only production database
    - name: prod
      targetContainerName: nginx
      targetContainerPort: 80
      hostTemplates:
        - "template-{{.BranchName}}.review.example.com"
      template:
        spec:
          # It's recommended to run your staging containers on a separate node pool
          # nodeSelector:
          #   node-role.kubernetes.io/staging: "true"
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
    - name: staging
      targetContainerName: nginx
      targetContainerPort: 80
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:1.20
              ports:
                - containerPort: 80
            - name: redis
              image: redis:6
        metadata:
          labels:
            pod-label: pod-label
          annotations:
            pod-annotation: pod-annotation
    # A staging environment pointing to your staging database
