apiVersion: rac.william.nu/v1alpha1
kind: ReviewApp
metadata:
  name: reviewapp-sample
  labels:
    mylabel: mylabel
spec:
  domain: review.example.com
  ingressConfig:
    tlsSecretName: reviewapp-sample-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    # ingressClassName:
    # defaultBackend:
  deployments:
    # A staging environment pointing to your read only production database
    - name: prod
      targetContainerName: nginx
      targetContainerPort: 80
      hostTemplates:
        - "template-{{branchName}}"
      spec:
        # It's recommended to run your staging containers on a separate node pool
        # nodeSelector:
        #   node-role.kubernetes.io/staging: "true"
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
    - name: staging
      targetContainerName: nginx
      targetContainerPort: 80
      spec:
        containers:
          - name: nginx
            image: nginx:1.20
            ports:
              - containerPort: 80
          - name: redis
            image: redis:6
    # A staging environment pointing to your staging database
