apiVersion: rac.william.nu/v1alpha1
kind: ReviewApp
metadata:
  name: reviewapp-sample
  labels:
    mylabel: mylabel
spec:
  github:
    githubToken: "githubToken"
  ingressConfig:
    hostnameSuffix: ".pr.bitrefill.com"
    # ingressClassName:
    # defaultBackend:
  deployments:
    # A staging environment pointing to your read only production database
    - name: prod
      targetContainerName: nginx
      targetPort: 80
      spec:
        # It's recommended to run your staging containers on a separate node pool
        # nodeSelector:
        #   node-role.kubernetes.io/staging: "true"
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
    - name: staging
      targetContainerName: nginx
      targetPort: 8080
      spec:
        containers:
          - name: nginx
            image: nginx:1.20
            ports:
              - containerPort: 8080
    # A staging environment pointing to your staging database
